.travis.yml:
  sudo: true
  dist: trusty
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE=small
      # Integration test matrix
      #
      # Mesos releases occur every two months, and each minor release is supported for six months.
      # For more info, see: http://mesos.apache.org/documentation/latest/versioning/
      #
      # Fortunately, Mesosphere doesn't remove previous releases from its Apt repositories.
      # Determine the version string to use here by running `apt-get update && apt-cache policy mesos`
      - TEST_TYPE=medium MESOS_RELEASE=0.28.1-2.0.20.ubuntu1404
Makefile:
  unmanaged: true
scripts/test.sh:
  unmanaged: true
